### ISSUE TITLE
Unexpected behaviour with API-Gateway Custom Domain Name Mapping

### ISSUE THREAD

**Issue by art-dc** [spring-media/aws-lambda-router#27] opened 2019-10-30 13:31 UTC
Hi,

Recently we found out that the first parameter from the `event.path` was ignored. After a quick inspectation of the `lib/proxyIntegration.js` file, I found an "ugly hack" which caused this behaviour, along with the following comment:

> ugly hack: if host is from API-Gateway 'Custom Domain Name Mapping', then event.path has the value '/basepath/resource-path/';
> if host is from amazonaws.com, then event.path is just '/resource-path':

My guess is this function is necessary for cases where users of aws-lambda-router use the API-gateway like this: http://customdomain.com/[stage]/[...parameters] (i.e. using the stage in between the custom domain and the parameters). However, in my case only the `prod` stage should be published on the custom domain. That's why I created a base path mapping in my Custom Domain options which maps the `/` path to `mylambdafunctionname:prod` (the `prod` stage of my API). This is why I don't have the stage name in my custom url and I think this is what causes the code to (in my case undesirable) remove the first parameter. But this is just my guess. I'm not entirely sure what is meant by `basepath` in the "ugly hack" comment, but regardless of whether it's because of me not having the stage in my custom url or it's because of something else, my point regarding unexpected first parameter removal still stands.

I'd be glad to hear if more details are needed to debug this case.

**Comment by mohitp-cci** [comment] 2019-11-13 05:57
any update on this? even i am facing the same issue.

**Comment by ArtZeeman** [comment] 2019-11-20 14:47
> any update on this? even i am facing the same issue.

Hey @mohitp-cci,

I've cloned the repository, made a minor tweak (comment out the "ugly hack" as it is not needed in my/your situation) and uploaded it to the NPM registry.

Its available with `npm install @dutchconcepts/aws-lambda-router`

You can view my code changes at [here](https://github.com/ArtZeeman/aws-lambda-router/commit/c82ef5056847d87e2ee47b5f2bb25f14c143786c). Beware I've disabled jasmine testing as well with [this commit](https://github.com/ArtZeeman/aws-lambda-router/commit/43745f2c0dfd8efe35e4bd9d91840b7732651d8f). I did this because this specific code for AWS gateway is tested, causing the test to fail.

**Comment by swaner** [comment] 2019-11-25 09:04
Are you using a proxy integration? https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-create-api-as-simple-proxy-for-http.html

If so, I did a pull-request that has been merged where you can specify the proxy path. This should work for custom domains as well. See https://github.com/spring-media/aws-lambda-router/pull/26

In api gateway the resource should be defined like this:
`/somebasepath/{proxy+}`

This allows the route to be written without the base part, so we can write the route like this:
proxyIntegration: `{ proxyPath: 'proxy', routes: [ { path: 'generate', ...`
Instead of the old way:
`{ routes: [ { path: '/somebasepath/generate', ...`

PR: https://github.com/spring-media/aws-lambda-router/pull/26

**Comment by ArtZeeman** [comment] 2020-05-18 09:47
Hi,

Thanks for your reply. I've tested the new version of aws-lambda-router that includes your pull request just now. I've noticed that the thing you've achieved with your pull request differs from my issue. 

Lambda's are usually deployed to an url like 
https://xxxxxxxx.execute-api.eu-central-1.amazonaws.com/dev/{proxy+}

Where `dev` is the stage, either `dev`, `prod` or something else. When the router tries to match the requested url in `event.path` with the routes supplied to aws-lambda-router, it removes the first parameters (dev or prod or something else) because that parameter will not be supplied in the router handlers.

However, if you supply a custom domain in API Gateway, there are three options.
- API
- Stage
- Path

The API is just the Lambda application. The path is probably what you are using in proxyPath: if you want https://example.com/v1/{proxy+} to all redirect to a certain lambda without the need to put `/v1/` in all your routes in your lambda's handler.

Lastly, the Stage option, can be selected to make sure that https://api.example.com uses the prod stage whereas https://api-test.example.com uses the dev stage.

This way the stage does not have to be supplied in the request url, like https://api-test.example.com/dev/{proxy+}. And while the stage is not supplied, aws-lambda-router's code still (wrongly) removes the first parameter from the request url, causing a mismatch with the routes.

**Comment by gravitycode** [comment] 2020-06-25 11:45
I did not understand this ugly hack and it has brought me a lot of headaches already. Couldn't we have a variable that disables this behavior?

**Comment by ArtZeeman** [comment] 2020-08-19 09:28
@gravitycode I'd love to see an option to disable it in a future version as well.

**Comment by EthanDavis** [comment] 2021-06-21 18:28
I believe I'm running into the same or similar issue. I have an api gateway instance setup with a custom domain.

my routes are: 
/api/health (GET)
/api/events (POST)

when I call https://custom-domain.com/api/events 

I'm hitting the lambda but it's returning the following error: 

```
{
    "message": "Could not find matching action for /events and method POST",
    "error": "NO_MATCHING_ACTION"
}
```

It seems like the router is removing the base /api? Or it's not getting passed through. Though I believe the issue is the former. When I add a base path mapping to my api gateway instance for /api then if I call:
https://custom-domain.com/api/api/events it succeeds. Any idea how I can fix this?

**Comment by EthanDavis** [comment] 2021-06-30 16:25
I've created a PR that implements your suggestion of having the ability to disable the removal of the base path. 

See here: https://github.com/spring-media/aws-lambda-router/pull/72

**Comment by chgohlke** [comment] 2021-08-19 14:36
The PR #72 is closed now. To avoid the behaviour please use the following configuration of `proxyIntegration`:
```
proxyIntegration({
      removeBasePath: true,
      routes: [{
        ...
      }]
}
```

**Comment by EthanDavis** [comment] 2021-10-01 20:27
Created a PR adding documentation for `removeBasePath` in readme

https://github.com/spring-media/aws-lambda-router/pull/77

**Closed** 2023-06-29 09:39 UTC
